# -----------------------------
# Application Configuration
# -----------------------------

# Repository type (cache or database)
repository.type=database

# Database Configuration (H2)

db.url=jdbc:h2:./data/quantitydb
db.username=sa
db.password=

# Connection Pool Configuration

db.pool.size=5
db.pool.timeout=30000

# Logging Configuration

logging.level.root=INFO
logging.level.com.apps.quantitymeasurement=DEBUG